import { Aplicacion, Servicio } from "@/interfaces";

export const serviciosSeed: Servicio[] = [
  {
    id: "1",
    nombre: "Auth Gateway",
    descripcion: "Manejo de sesiones y OAuth2.",
    url: "https://auth.dev.com",
    ambiente: "DEV",
    notas: "Soporta Google y GitHub.",
  },
  {
    id: "2",
    nombre: "Payment Processor",
    descripcion: "Integración con Stripe.",
    url: "https://pay.stg.com",
    ambiente: "QA",
    notas: "Solo usar tarjetas de test.",
  },
  {
    id: "3",
    nombre: "Push Notifications",
    descripcion: "Envío de alertas vía FCM.",
    url: "https://push.prod.com",
    ambiente: "PRD",
  },
  {
    id: "4",
    nombre: "Inventory API",
    descripcion: "Control de stock en tiempo real.",
    url: "http://localhost:4000",
    ambiente: "DEV",
  },
  {
    id: "5",
    nombre: "Email Worker",
    descripcion: "Cola de correos pendientes.",
    url: "https://mail.qa.com",
    ambiente: "QA",
    notas: "Usa plantillas de SendGrid.",
  },
  {
    id: "6",
    nombre: "Analytics Engine",
    descripcion: "Cálculo de métricas mensuales.",
    url: "https://stats.prod.com",
    ambiente: "PRD",
  },
  {
    id: "7",
    nombre: "Image Optimizer",
    descripcion: "Redimensión de assets en S3.",
    url: "https://img.dev.com",
    ambiente: "DEV",
  },
  {
    id: "8",
    nombre: "User Profile Service",
    descripcion: "Gestión de datos de usuario.",
    url: "http://localhost:3005",
    ambiente: "DEV",
    notas: "Conectado a MongoDB.",
  },
  {
    id: "9",
    nombre: "Tax Calculator",
    descripcion: "Cálculo de IVA y retenciones.",
    url: "https://tax.stg.com",
    ambiente: "QA",
  },
  {
    id: "10",
    nombre: "Shipping Tracker",
    descripcion: "Rastreo de paquetes externos.",
    url: "https://ship.prod.com",
    ambiente: "PRD",
    notas: "API de DHL y FedEx.",
  },
  {
    id: "11",
    nombre: "Logging Central",
    descripcion: "Agregador de logs (ELK).",
    url: "https://logs.dev.com",
    ambiente: "QA",
  },
  {
    id: "12",
    nombre: "Billing Service",
    descripcion: "Generación de facturas PDF.",
    url: "https://billing.qa.com",
    ambiente: "QA",
  },
  {
    id: "13",
    nombre: "Search Microservice",
    descripcion: "Búsqueda con ElasticSearch.",
    url: "http://localhost:9200",
    ambiente: "QA",
  },
  {
    id: "14",
    nombre: "Carts API",
    descripcion: "Manejo de carritos de compra.",
    url: "https://cart.stg.com",
    ambiente: "QA",
  },
  {
    id: "15",
    nombre: "Security Audit",
    descripcion: "Escaneo de vulnerabilidades.",
    url: "https://audit.prod.com",
    ambiente: "PRD",
    notas: "Reportes cada 24h.",
  },
  {
    id: "16",
    nombre: "Localization Service",
    descripcion: "Traducciones y i18n.",
    url: "https://i18n.dev.com",
    ambiente: "DEV",
  },
  {
    id: "17",
    nombre: "Reporting Tool",
    descripcion: "Exportación de datos a Excel.",
    url: "https://reports.qa.com",
    ambiente: "QA",
  },
  {
    id: "18",
    nombre: "Customer Support Chat",
    descripcion: "Backend para WebSockets.",
    url: "https://chat.prod.com",
    ambiente: "PRD",
  },
  {
    id: "19",
    nombre: "Legacy Database Proxy",
    descripcion: "Puente hacia SQL Server antiguo.",
    url: "http://localhost:8080",
    ambiente: "QA",
  },
  {
    id: "20",
    nombre: "Review System",
    descripcion: "Gestión de reseñas de productos.",
    url: "https://reviews.stg.com",
    ambiente: "QA",
  },
  {
    id: "21",
    nombre: "Fraud Detection",
    descripcion: "IA para detección de fraudes.",
    url: "https://fraud.prod.com",
    ambiente: "PRD",
    notas: "Modelo de ML actualizado.",
  },
  {
    id: "22",
    nombre: "Geo Service",
    descripcion: "Conversión de IP a ubicación.",
    url: "https://geo.dev.com",
    ambiente: "DEV",
  },
  {
    id: "23",
    nombre: "Coupon Manager",
    descripcion: "Validación de códigos de descuento.",
    url: "https://coupons.qa.com",
    ambiente: "QA",
  },
  {
    id: "24",
    nombre: "Catalog API",
    descripcion: "Listado maestro de productos.",
    url: "https://catalog.prod.com",
    ambiente: "PRD",
  },
  {
    id: "25",
    nombre: "Developer Sandbox",
    descripcion: "Entorno de pruebas para terceros.",
    url: "https://sandbox.stg.com",
    ambiente: "QA",
    notas: "Reset de base de datos semanal.",
  },
];

export const aplicacionesSeed: Aplicacion[] = [
  {
    id: "1",
    nombre: "Mi Abank Digital",
    version: "2.5.0-alpha",
    ambiente: "DEV",
  },
  {
    id: "2",
    nombre: "Dashboard de Administración",
    version: "1.2.0-beta",
    ambiente: "QA",
  },
  {
    id: "3",
    nombre: "Portal de Clientes",
    version: "3.0.0",
    ambiente: "PRD",
  },
];
